Study 1
Parkjunhu/portfolio pull request #2
Opened 2020-10-27 11:06 UTC by Parkjunhu

study_1 브랜치를 main 브랜치에 합치겠다.

2020-10-28 10:57 UTC, Joker-lucas requested changes
몇몇사항 코멘트남겼어요! 수정해서 다시 푸시해주시면됩니다~

2020-10-28 10:57 UTC, Joker-lucas commented on index.html
> +    <section id="3" style="background-color : orange; padding : 10vh 0">
id를 그냥 숫자로 쓰는거보다 의미있는용어를 쓰는게좋습니다. 
예를 들면 photoWrap 이런식으로.. 나중에 DOM다룰때 명확한게 좋습니다!

2020-10-28 10:57 UTC, Joker-lucas commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 60.375px;" >
margin top이 소수점으로 들어가있는데 저렇게하신이유가있을까요? 엄청디테일한게아니면 일반 정수단위로 쓰시는게어떨까요 ㅎㅎ

2020-10-28 10:57 UTC, Joker-lucas commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 30.1875px;" >
전체적으로 height잡으신거보니 vh 단위를 쓰셨네요 vw와 마찬가지로 각자의 화면에서 높이를 계산하여 퍼센테이지를 매기는건데, 높이같은경우는 반응형에서 조금 자유로운편입니다. 
잘못됬다는건아닌데 추후 개발하면서 수정하는게 나을수도있어요~

2020-10-28 10:57 UTC, Joker-lucas commented on index.html
> +    <header style="background-color : green; height : 100vh;">
이 부분이 header인것은 맞지않아보입니다. slide 영역은 header랑 다르니 다른 태그로하는게 좋을거같습니다. 
참고로 header태그가 꼭있어야하는것은 아닙니다!

2020-10-28 10:58 UTC, Joker-lucas commented
전체적으로 소스확인과 구성을 확인했을때 잘 해주셨습니다. 결과물을 확인해보니 레이아웃이 잘잡혀있네요. 수고하셨습니다!

2020-10-28 11:25 UTC, Parkjunhu commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 30.1875px;" >
vh 말고 px로 써도 상관없는건가요?

2020-10-28 11:36 UTC, Parkjunhu commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 60.375px;" >
아마.. 
<div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 60.375px;" >
            <article style="background-color :red; width : 47%;  height : 100%;  margin-right : 3%; float : left; "> 
            </article>
            <article style="background-color :blue; width : 47%; height : 100%; margin-left : 3%; float : left;"> 
            </article>
        </div>

margin-right : 3%, margin-left : 3%에 의한 간격을 개발자도구를 보고 픽셀값을 알아내서
저렇게 소수점 값으로 지정해주었던거 같아요..ㅎ 엄청 디테일하게 해야하는건가해서 저렇게했는데. 60px만 줘도 얼추맞을거 같긴합니다..

2020-10-28 12:02 UTC, Parkjunhu commented on index.html
> +    <section id="3" style="background-color : orange; padding : 10vh 0">
의미있는 ID값으로 변경하였습니다. (수정 1차)

2020-10-28 12:03 UTC, Parkjunhu commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 60.375px;" >
소수점 값을 뺀 나머지 정수값으로 수정했습니다. (수정 1차)

2020-10-28 12:12 UTC, Parkjunhu commented on index.html
> +    <header style="background-color : green; height : 100vh;">
header 태그를 div 태그로 수정했습니다.(1차 수정 : 2020-10-28 21:12)

2020-10-28 12:36 UTC, Joker-lucas commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 30.1875px;" >
vh든 px든 어떤게 다른하나를 완벽하게 대체할순없어요! 상황에 따라 맞게써야하는건데 유동적으로 항상 화면사이즈에 맞춰서 움직어야하면 vh 그게아니라면 px을쓰는거죠. 근데 높이는 상대적으로자유도가 높기에 꼭 화면 비율에 맞출필요는 없다는것을 말씀드리고싶었습니다

2020-10-28 13:03 UTC, Parkjunhu commented on index.html
> +        <div style="height : 40vh; width : 75%; margin: 0 auto; margin-top : 60.375px;" >
margin-top 값 단위를 px -> vh로 변경 (2차 수정 : 2020-10-28 21:52)

2020-10-30 15:18 UTC, Joker-lucas approved these changes
전체적으로 잘따라와 주신게 보여서 다행입니다. 아무래도 비즈니스 로직적인 부분이아니다보니 더 나은부분에 대해서 제안정도의 리뷰가 대부분일거같네요.
결과물도 확인해보았는데 전체적인 레이아웃은 잡힌거같습니다. 다음스터디에서 더디벨롭해보죠 ! 수고하셨어요

2020-10-31 03:13 UTC, merged